---
- name: Find existing VMPools
  ovirt_vmpool_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "datacenter={{ data_center_name }}"

- name: Remove VMPools
  ovirt_vmpool:
    state: absent
    name: "{{ ovirt_item.name }}"
    auth: "{{ ovirt_auth }}"
  with_items: "{{ ovirt_vm_pools }}"
  loop_control:
    loop_var: ovirt_item
