---
- name: Find existing VMs
  ovirt_vm_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "datacenter={{ data_center_name }}"

- name: Remove VMs
  ovirt_vm:
    state: absent
    id: "{{ ovirt_item.id }}"
    auth: "{{ ovirt_auth }}"
  with_items: "{{ ovirt_vms }}"
  loop_control:
    loop_var: ovirt_item
